import Foundation

/// 2026-07-22 — translation strings for the core project/scene/shot/team
/// workflow (ProjectListView, ShotListView, SceneEditSheet, ShotDetailSheet,
/// SectionEditSheet, ProjectEditSheet, ProjectInfoBox, FolderEditSheet,
/// TeamSheet, ShareLinkSheet). See AppLanguage.swift's own doc comment for
/// why this lives in its own file instead of one shared dictionary, and
/// AvatarMenu.swift for the reference implementation this pass follows.
/// Wording matches subshot-web's lib/i18n.tsx wherever the same real-world
/// concept exists there (same component pairing noted per section below),
/// so the same thing reads the same way on both platforms.
/// UNVERIFIED — no compiler here, see project memory (iOS: no compiler here).
extension AppLanguage {
    static let projectCoreStrings: [String: [String: String]] = [
        "de": [
            // Shared across this whole pass — mirrors lib/i18n.tsx's
            // common.* / roles.* / scene.* / shot.* keys, reused verbatim
            // by several of the files below instead of one key per file.
            "common.cancel": "Abbrechen",
            "common.delete": "Löschen",
            "common.save": "Speichern",
            "common.done": "Fertig",
            "common.edit": "Bearbeiten",
            "common.confirm": "Bestätigen",
            "common.ok": "OK",
            "common.error": "Fehler",
            "common.duplicate": "Duplizieren",
            "common.remove": "Entfernen",
            "common.undo": "Rückgängig",
            "common.none": "Keine",
            "common.change": "Ändern",
            "common.addImage": "Bild hinzufügen",
            "common.changeImage": "Bild ändern",
            "common.removeImage": "Bild entfernen",
            "common.addressPlaceholder": "Adresse eingeben",
            "common.location": "Standort",
            "common.assignee": "Zuständig",
            "common.deletingInDays": "Wird gelöscht in {days} Tagen",
            "scene.unnamed": "Unbenannte Szene",
            "scene.goodTake": "Good Take",
            "shot.noDescription": "Ohne Beschreibung",
            "roles.projectLead": "Projektleiter",
            "roles.editor": "Editor",
            "roles.owner": "Besitzer",
            "nav.team": "Team",
            "assignee.nobodyAssigned": "Niemand zugewiesen",
            "insufficientCredits.title": "Keine Credits mehr",
            "insufficientCredits.later": "Später",
            "insufficientCredits.buyCredits": "Credits kaufen",

            // ProjectListView.swift
            "projectListView.emptyTitle": "Noch keine Projekte",
            "projectListView.emptyDescription": "Tippe auf + um dein erstes Projekt anzulegen.",
            "projectListView.newProject": "Neues Projekt",
            "projectListView.newFolder": "Neuer Ordner",

            // ShotListView.swift
            "shotListView.pdfCardView": "Kachelansicht",
            "shotListView.pdfTableView": "Tabellenansicht",
            "shotListView.goodTakeAlertTitle": "Good Take",
            "shotListView.goodTakePlaceholder": "Dateiname, z.B. A003_C012",
            "shotListView.goodTakeAlertMessage": "Dateiname der guten Aufnahme für diese Szene.",
            "shotListView.editDialogueLineTitle": "Dialogzeile bearbeiten",
            "shotListView.dialogueTextPlaceholder": "Dialogtext",
            "shotListView.timeCascadeTitle": "Möchtest du die nachfolgenden Szenen zeitlich angleichen?",
            "shotListView.timeCascadeDecline": "Nicht angleichen",
            "shotListView.allDoneTitle": "Alles im Kasten?",
            "shotListView.allDoneConfirm": "Alles im Kasten",
            "shotListView.allDoneMessage": "Alle Shots wirklich im Kasten, hast du auch wirklich keine Aussage oder Szene vergessen?",
            "shotListView.columnsCount": "{count} Spalten",
            "shotListView.newScene": "Neue Szene",
            "shotListView.newIntermediateStep": "Zwischenschritt",
            "shotListView.newSection": "Neuer Abschnitt",
            "shotListView.newInfo": "Info",
            "shotListView.rename": "Umbenennen",
            "shotListView.sendToPostproduction": "Ab in die Postproduction",
            "shotListView.sortByNumber": "Nach Identifikationsnummer sortieren",
            "shotListView.sortByTime": "Nach Zeit sortieren",
            "shotListView.sortByLocation": "Nach Ort sortieren",
            "shotListView.sortByPriority": "Nach Priorität sortieren",
            "shotListView.noSection": "Ohne Abschnitt",
            "shotListView.startAt": "Start: {date}",
            "shotListView.markNotDone": "Nicht mehr im Kasten",
            "shotListView.shotsHeader": "Einstellungen",
            "shotListView.moreCount": "+{count} weitere",
            "shotListView.descriptionHeader": "Beschreibung",
            "shotListView.dialogHeader": "Dialog",
            "shotListView.inTheCan": "Im Kasten",
            "shotListView.markAsOpen": "Als offen markieren",
            "shotListView.markAsDone": "Erledigt",
            "shotListView.shotFallbackName": "Einstellung",
            "shotListView.deletedToast": "„{name}“ gelöscht",
            "shotListView.deleteSectionTitle": "Abschnitt löschen?",
            "shotListView.deleteSectionMessage": "\"{name}\" wird gelöscht. Jegliche Szenen oder Kacheln im Abschnitt werden auch gelöscht.",
            "shotListView.deleteSceneTitle": "Szene löschen?",
            "shotListView.deleteSceneMessage": "\"{name}\" wird endgültig gelöscht, inklusive aller Einstellungen darin.",
            "shotListView.allSceneDoneTitle": "Alle Szenen im Kasten?",
            "shotListView.sendToPostproductionMessage": "\"{name}\" wandert in die Postproduction-Tracking-Liste.",
            "shotListView.goodTakeWithFilename": "Good Take: {filename}",
            "shotListView.plannedTime": "Geplante Zeit: {duration}",
            "shotListView.minutesShort": "{count} Min.",
            "shotListView.shootTimeElapsed": "Drehzeit abgelaufen",
            "shotListView.remainingTime": "Verbleibend: {time}",

            // SceneEditSheet.swift
            "sceneEditSheet.imageSection": "Bild",
            "sceneEditSheet.aiImageFromDescription": "KI-Bild aus Beschreibung erstellen",
            "sceneEditSheet.formatPicker": "Format",
            "sceneEditSheet.stylePicker": "Stil",
            "sceneEditSheet.styleRealistic": "Realistisch",
            "sceneEditSheet.styleSketch": "Sketch",
            "sceneEditSheet.generating": "Erstellt…",
            "sceneEditSheet.generateImage": "Bild generieren",
            "sceneEditSheet.needsDescriptionFirst": "Erst eine Beschreibung eintragen",
            "sceneEditSheet.nameSection": "Name",
            "sceneEditSheet.namePlaceholder": "z.B. Küche, Aussen Tag 1",
            "sceneEditSheet.prioritySection": "Priorität",
            "sceneEditSheet.descriptionSection": "Beschreibung",
            "sceneEditSheet.descriptionPlaceholder": "z.B. Handlung, Notizen",
            "sceneEditSheet.newDialoguePlaceholder": "Neuer Dialog",
            "sceneEditSheet.doubleEnterHint": "Zweimal Enter schliesst den Dialog ab.",
            "sceneEditSheet.dialogueButtonLabel": "Dialog",
            "sceneEditSheet.dialogHeader": "Dialog",
            "sceneEditSheet.dateSection": "Datum & Uhrzeit",
            "sceneEditSheet.setShootDate": "Drehtermin festlegen",
            "sceneEditSheet.startLabel": "Start",
            "sceneEditSheet.estimatedDurationSection": "Geschätzte Länge",
            "sceneEditSheet.hoursPicker": "Stunden",
            "sceneEditSheet.hoursShort": "{count} Std.",
            "sceneEditSheet.minutesPicker": "Minuten",
            "sceneEditSheet.minutesShort": "{count} Min.",
            "sceneEditSheet.locationSection": "Standort",
            "sceneEditSheet.nobodyOption": "Niemand",
            "sceneEditSheet.shotsSection": "Einstellungen",
            "sceneEditSheet.newShotPlaceholder": "Neue Einstellung",
            "sceneEditSheet.addShotButton": "Einstellung hinzufügen",
            "sceneEditSheet.editTitle": "Szene bearbeiten",
            "sceneEditSheet.newIntermediateTitle": "Neuer Zwischenschritt",
            "sceneEditSheet.newTitle": "Neue Szene",
            "sceneEditSheet.insufficientCreditsMessage": "Du hast keine AI Credits mehr übrig, um ein Bild zu generieren. Lade Credits über die Web-Seite nach.",

            // ShotDetailSheet.swift
            "shotDetailSheet.imageSection": "Bild",
            "shotDetailSheet.addPhoto": "Foto hinzufügen",
            "shotDetailSheet.changePhoto": "Foto ändern",
            "shotDetailSheet.removePhoto": "Foto entfernen",
            "shotDetailSheet.descriptionSection": "Beschreibung",
            "shotDetailSheet.descriptionPlaceholder": "z.B. Weitwinkel Establishing Shot",
            "shotDetailSheet.prioritySection": "Priorität",
            "shotDetailSheet.goodTakeSection": "Good Take:",
            "shotDetailSheet.goodTakePlaceholder": "Dateiname, z.B. A003_C012",
            "shotDetailSheet.cameraSection": "Kamera",
            "shotDetailSheet.cameraIdPlaceholder": "Kamera-ID (A, B, C…)",
            "shotDetailSheet.lensPicker": "Objektiv",
            "shotDetailSheet.fstopPicker": "F-Stop",
            "shotDetailSheet.frameratePicker": "Framerate",
            "shotDetailSheet.shutterAnglePlaceholder": "Shutterangle",
            "shotDetailSheet.isoPicker": "ISO",
            "shotDetailSheet.codecPlaceholder": "Codec",
            "shotDetailSheet.cameraSupportPicker": "Aufnahme-Art",
            "shotDetailSheet.title": "Einstellung bearbeiten",

            // SectionEditSheet.swift
            "sectionEditSheet.nameSection": "Name",
            "sectionEditSheet.namePlaceholder": "z.B. Tag 1, Interieur, Nachtdreh",
            "sectionEditSheet.newTitle": "Neuer Abschnitt",
            "sectionEditSheet.renameTitle": "Abschnitt umbenennen",

            // ProjectEditSheet.swift
            "projectEditSheet.nameSection": "Name",
            "projectEditSheet.namePlaceholder": "Projektname",
            "projectEditSheet.emojiSection": "Emoji",
            "projectEditSheet.colorSection": "Farbe",
            "projectEditSheet.pipelineModulesSection": "Pipeline-Module",
            "projectEditSheet.moduleConcept": "Konzept",
            "projectEditSheet.moduleScripting": "Script/Shotlist",
            "projectEditSheet.modulePostproduction": "Postproduction Tracking",
            "projectEditSheet.newTitle": "Neues Projekt",
            "projectEditSheet.editTitle": "Projekt bearbeiten",

            // FolderEditSheet.swift
            "folderEditSheet.backgroundImageSection": "Hintergrundbild",
            "folderEditSheet.nameSection": "Name",
            "folderEditSheet.namePlaceholder": "z.B. Kunde XY",
            "folderEditSheet.emojiSection": "Emoji",
            "folderEditSheet.colorSection": "Farbe",
            "folderEditSheet.newTitle": "Neuer Ordner",
            "folderEditSheet.editTitle": "Ordner bearbeiten",

            // TeamSheet.swift
            "teamSheet.membersSection": "Mitglieder",
            "teamSheet.invitePersonSection": "Person einladen",
            "teamSheet.selectPerson": "Person auswählen",
            "teamSheet.emailPlaceholder": "E-Mail-Adresse",
            "teamSheet.roleLabel": "Rolle",
            "teamSheet.inviteButton": "Einladen",
            "teamSheet.inviteLinkSection": "Einladungslink (manuell teilen)",

            // ShareLinkSheet.swift
            "shareLinkSheet.copied": "Kopiert",
            "shareLinkSheet.copyLink": "Link kopieren",
            "shareLinkSheet.share": "Teilen",
            "shareLinkSheet.publicLinkHeader": "Öffentlicher Link",
            "shareLinkSheet.linkHint": "Jeder mit diesem Link kann die Vorschau ansehen, auch ohne Subshot-Account. Läuft nach 7 Tagen ab.",
            "shareLinkSheet.protectWithPassword": "Mit Passwort schützen",
            "shareLinkSheet.newPasswordOptional": "Neues Passwort (optional)",
            "shareLinkSheet.passwordPlaceholder": "Passwort",
            "shareLinkSheet.saved": "Gespeichert",
            "shareLinkSheet.changePassword": "Passwort ändern",
            "shareLinkSheet.setPassword": "Passwort setzen",
            "shareLinkSheet.passwordProtectionHeader": "Passwortschutz",
            "shareLinkSheet.protectedHint": "Aktiv — Besucher müssen das Passwort eingeben, bevor sie die Vorschau sehen.",
            "shareLinkSheet.unprotectedHint": "Sinnvoll für Projekte/Kunden, wo nichts öffentlich einsehbar sein soll, auch nicht mit dem Link.",
            "shareLinkSheet.titleIdeas": "Ideen-Link teilen",
            "shareLinkSheet.titleVideo": "Video-Feedback-Link teilen",
            "shareLinkSheet.titleDefault": "Link teilen",

            // ProjectInfoBox.swift (also covers SectionInfoBox / SceneProjectInfoTile,
            // defined in the same file)
            "projectInfoBox.title": "Projektinfos",
            "projectInfoBox.infoTitle": "Info",
            "projectInfoBox.infoTitleFor": "Info: {name}",
            "projectInfoBox.deleteConfirmTitle": "Projektinfo löschen?",
            "projectInfoBox.deleteConfirmMessage": "Datum, Ort und Todo-Listen dieser Projektinfo werden entfernt.",
            "projectInfoBox.peopleLabel": "Personen",
            "projectInfoBox.shootDateLabel": "Drehdatum",
            "projectInfoBox.setDateToggle": "Datum festlegen",
            "projectInfoBox.startLabel": "Start",
            "projectInfoBox.clientLabel": "Auftraggeber",
            "projectInfoBox.clientPlaceholder": "Name des Auftraggebers",
            "projectInfoBox.todoListsLabel": "Todo-Listen",
            "projectInfoBox.listNamePlaceholder": "Listenname",
            "projectInfoBox.addListButton": "Liste hinzufügen",
            "projectInfoBox.newItemPlaceholder": "Neuer Punkt",
            "projectInfoBox.addItemButton": "Punkt hinzufügen",
            "projectInfoBox.assignAria": "Zuweisen",
        ],
        "en": [
            "common.cancel": "Cancel",
            "common.delete": "Delete",
            "common.save": "Save",
            "common.done": "Done",
            "common.edit": "Edit",
            "common.confirm": "Confirm",
            "common.ok": "OK",
            "common.error": "Error",
            "common.duplicate": "Duplicate",
            "common.remove": "Remove",
            "common.undo": "Undo",
            "common.none": "None",
            "common.change": "Change",
            "common.addImage": "Add image",
            "common.changeImage": "Change image",
            "common.removeImage": "Remove image",
            "common.addressPlaceholder": "Enter address",
            "common.location": "Location",
            "common.assignee": "Assigned to",
            "common.deletingInDays": "Will be deleted in {days} days",
            "scene.unnamed": "Untitled scene",
            "scene.goodTake": "Good take",
            "shot.noDescription": "No description",
            "roles.projectLead": "Project lead",
            "roles.editor": "Editor",
            "roles.owner": "Owner",
            "nav.team": "Team",
            "assignee.nobodyAssigned": "No one assigned",
            "insufficientCredits.title": "No credits left",
            "insufficientCredits.later": "Later",
            "insufficientCredits.buyCredits": "Buy credits",

            // ProjectListView.swift
            "projectListView.emptyTitle": "No projects yet",
            "projectListView.emptyDescription": "Tap + to create your first project.",
            "projectListView.newProject": "New project",
            "projectListView.newFolder": "New folder",

            // ShotListView.swift
            "shotListView.pdfCardView": "Card view",
            "shotListView.pdfTableView": "Table view",
            "shotListView.goodTakeAlertTitle": "Good take",
            "shotListView.goodTakePlaceholder": "Filename, e.g. A003_C012",
            "shotListView.goodTakeAlertMessage": "Filename of the keeper take for this scene.",
            "shotListView.editDialogueLineTitle": "Edit dialogue line",
            "shotListView.dialogueTextPlaceholder": "Dialogue text",
            "shotListView.timeCascadeTitle": "Shift the following scenes to match?",
            "shotListView.timeCascadeDecline": "Don't shift",
            "shotListView.allDoneTitle": "Everything in the can?",
            "shotListView.allDoneConfirm": "Everything in the can",
            "shotListView.allDoneMessage": "Are all shots really wrapped — sure you haven't forgotten a line or a scene?",
            "shotListView.columnsCount": "{count} columns",
            "shotListView.newScene": "New scene",
            "shotListView.newIntermediateStep": "Intermediate step",
            "shotListView.newSection": "New section",
            "shotListView.newInfo": "Info",
            "shotListView.rename": "Rename",
            "shotListView.sendToPostproduction": "Send to postproduction",
            "shotListView.sortByNumber": "Sort by ID number",
            "shotListView.sortByTime": "Sort by time",
            "shotListView.sortByLocation": "Sort by location",
            "shotListView.sortByPriority": "Sort by priority",
            "shotListView.noSection": "No section",
            "shotListView.startAt": "Start: {date}",
            "shotListView.markNotDone": "No longer in the can",
            "shotListView.shotsHeader": "Shots",
            "shotListView.moreCount": "+{count} more",
            "shotListView.descriptionHeader": "Description",
            "shotListView.dialogHeader": "Dialogue",
            "shotListView.inTheCan": "Wrapped",
            "shotListView.markAsOpen": "Mark as open",
            "shotListView.markAsDone": "Done",
            "shotListView.shotFallbackName": "Shot",
            "shotListView.deletedToast": "“{name}” deleted",
            "shotListView.deleteSectionTitle": "Delete section?",
            "shotListView.deleteSectionMessage": "\"{name}\" will be deleted. Any scenes or tiles in the section will be deleted too.",
            "shotListView.deleteSceneTitle": "Delete scene?",
            "shotListView.deleteSceneMessage": "\"{name}\" will be permanently deleted, including all shots in it.",
            "shotListView.allSceneDoneTitle": "All scenes in the can?",
            "shotListView.sendToPostproductionMessage": "\"{name}\" moves to the postproduction tracking list.",
            "shotListView.goodTakeWithFilename": "Good take: {filename}",
            "shotListView.plannedTime": "Planned time: {duration}",
            "shotListView.minutesShort": "{count} min",
            "shotListView.shootTimeElapsed": "Shoot time elapsed",
            "shotListView.remainingTime": "Remaining: {time}",

            // SceneEditSheet.swift
            "sceneEditSheet.imageSection": "Image",
            "sceneEditSheet.aiImageFromDescription": "Generate AI image from description",
            "sceneEditSheet.formatPicker": "Format",
            "sceneEditSheet.stylePicker": "Style",
            "sceneEditSheet.styleRealistic": "Realistic",
            "sceneEditSheet.styleSketch": "Sketch",
            "sceneEditSheet.generating": "Generating…",
            "sceneEditSheet.generateImage": "Generate image",
            "sceneEditSheet.needsDescriptionFirst": "Enter a description first",
            "sceneEditSheet.nameSection": "Name",
            "sceneEditSheet.namePlaceholder": "e.g. kitchen, exterior day 1",
            "sceneEditSheet.prioritySection": "Priority",
            "sceneEditSheet.descriptionSection": "Description",
            "sceneEditSheet.descriptionPlaceholder": "e.g. action, notes",
            "sceneEditSheet.newDialoguePlaceholder": "New dialogue line",
            "sceneEditSheet.doubleEnterHint": "Press Enter twice to close the dialogue.",
            "sceneEditSheet.dialogueButtonLabel": "Dialogue",
            "sceneEditSheet.dialogHeader": "Dialogue",
            "sceneEditSheet.dateSection": "Date & time",
            "sceneEditSheet.setShootDate": "Set shoot date",
            "sceneEditSheet.startLabel": "Start",
            "sceneEditSheet.estimatedDurationSection": "Estimated duration",
            "sceneEditSheet.hoursPicker": "Hours",
            "sceneEditSheet.hoursShort": "{count} hr",
            "sceneEditSheet.minutesPicker": "Minutes",
            "sceneEditSheet.minutesShort": "{count} min",
            "sceneEditSheet.locationSection": "Location",
            "sceneEditSheet.nobodyOption": "Nobody",
            "sceneEditSheet.shotsSection": "Shots",
            "sceneEditSheet.newShotPlaceholder": "New shot",
            "sceneEditSheet.addShotButton": "Add shot",
            "sceneEditSheet.editTitle": "Edit scene",
            "sceneEditSheet.newIntermediateTitle": "New intermediate step",
            "sceneEditSheet.newTitle": "New scene",
            "sceneEditSheet.insufficientCreditsMessage": "You have no AI credits left to generate an image. Top up credits via the website.",

            // ShotDetailSheet.swift
            "shotDetailSheet.imageSection": "Image",
            "shotDetailSheet.addPhoto": "Add photo",
            "shotDetailSheet.changePhoto": "Change photo",
            "shotDetailSheet.removePhoto": "Remove photo",
            "shotDetailSheet.descriptionSection": "Description",
            "shotDetailSheet.descriptionPlaceholder": "e.g. wide establishing shot",
            "shotDetailSheet.prioritySection": "Priority",
            "shotDetailSheet.goodTakeSection": "Good take:",
            "shotDetailSheet.goodTakePlaceholder": "Filename, e.g. A003_C012",
            "shotDetailSheet.cameraSection": "Camera",
            "shotDetailSheet.cameraIdPlaceholder": "Camera ID (A, B, C…)",
            "shotDetailSheet.lensPicker": "Lens",
            "shotDetailSheet.fstopPicker": "F-stop",
            "shotDetailSheet.frameratePicker": "Frame rate",
            "shotDetailSheet.shutterAnglePlaceholder": "Shutter angle",
            "shotDetailSheet.isoPicker": "ISO",
            "shotDetailSheet.codecPlaceholder": "Codec",
            "shotDetailSheet.cameraSupportPicker": "Support type",
            "shotDetailSheet.title": "Edit shot",

            // SectionEditSheet.swift
            "sectionEditSheet.nameSection": "Name",
            "sectionEditSheet.namePlaceholder": "e.g. Day 1, interior, night shoot",
            "sectionEditSheet.newTitle": "New section",
            "sectionEditSheet.renameTitle": "Rename section",

            // ProjectEditSheet.swift
            "projectEditSheet.nameSection": "Name",
            "projectEditSheet.namePlaceholder": "Project name",
            "projectEditSheet.emojiSection": "Emoji",
            "projectEditSheet.colorSection": "Color",
            "projectEditSheet.pipelineModulesSection": "Pipeline modules",
            "projectEditSheet.moduleConcept": "Concept",
            "projectEditSheet.moduleScripting": "Script/Shot list",
            "projectEditSheet.modulePostproduction": "Postproduction tracking",
            "projectEditSheet.newTitle": "New project",
            "projectEditSheet.editTitle": "Edit project",

            // FolderEditSheet.swift
            "folderEditSheet.backgroundImageSection": "Background image",
            "folderEditSheet.nameSection": "Name",
            "folderEditSheet.namePlaceholder": "e.g. Client XY",
            "folderEditSheet.emojiSection": "Emoji",
            "folderEditSheet.colorSection": "Color",
            "folderEditSheet.newTitle": "New folder",
            "folderEditSheet.editTitle": "Edit folder",

            // TeamSheet.swift
            "teamSheet.membersSection": "Members",
            "teamSheet.invitePersonSection": "Invite person",
            "teamSheet.selectPerson": "Select person",
            "teamSheet.emailPlaceholder": "Email address",
            "teamSheet.roleLabel": "Role",
            "teamSheet.inviteButton": "Invite",
            "teamSheet.inviteLinkSection": "Invite link (share manually)",

            // ShareLinkSheet.swift
            "shareLinkSheet.copied": "Copied",
            "shareLinkSheet.copyLink": "Copy link",
            "shareLinkSheet.share": "Share",
            "shareLinkSheet.publicLinkHeader": "Public link",
            "shareLinkSheet.linkHint": "Anyone with this link can view the preview, even without a Subshot account. Expires after 7 days.",
            "shareLinkSheet.protectWithPassword": "Protect with password",
            "shareLinkSheet.newPasswordOptional": "New password (optional)",
            "shareLinkSheet.passwordPlaceholder": "Password",
            "shareLinkSheet.saved": "Saved",
            "shareLinkSheet.changePassword": "Change password",
            "shareLinkSheet.setPassword": "Set password",
            "shareLinkSheet.passwordProtectionHeader": "Password protection",
            "shareLinkSheet.protectedHint": "Active — visitors must enter the password before they can see the preview.",
            "shareLinkSheet.unprotectedHint": "Useful for projects/clients where nothing should be publicly viewable, even with the link.",
            "shareLinkSheet.titleIdeas": "Share ideas link",
            "shareLinkSheet.titleVideo": "Share video feedback link",
            "shareLinkSheet.titleDefault": "Share link",

            // ProjectInfoBox.swift (also covers SectionInfoBox / SceneProjectInfoTile,
            // defined in the same file)
            "projectInfoBox.title": "Project info",
            "projectInfoBox.infoTitle": "Info",
            "projectInfoBox.infoTitleFor": "Info: {name}",
            "projectInfoBox.deleteConfirmTitle": "Delete project info?",
            "projectInfoBox.deleteConfirmMessage": "Date, location, and todo lists for this project info will be removed.",
            "projectInfoBox.peopleLabel": "People",
            "projectInfoBox.shootDateLabel": "Shoot date",
            "projectInfoBox.setDateToggle": "Set date",
            "projectInfoBox.startLabel": "Start",
            "projectInfoBox.clientLabel": "Client",
            "projectInfoBox.clientPlaceholder": "Client name",
            "projectInfoBox.todoListsLabel": "Todo lists",
            "projectInfoBox.listNamePlaceholder": "List name",
            "projectInfoBox.addListButton": "Add list",
            "projectInfoBox.newItemPlaceholder": "New item",
            "projectInfoBox.addItemButton": "Add item",
            "projectInfoBox.assignAria": "Assign",
        ],
    ]
}
